apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: tired-blackbird-nodejs 
  janus-idp.io/tekton: tired-blackbird-nodejs
  backstage.io/kubernetes-id: tired-blackbird-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: tired-blackbird-nodejs
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  